apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: iscsi-postgresql
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: iscsi
