apiVersion: v1
kind: Service
metadata:
  name: ignis-service
  namespace: lumines
  labels:
    app: ignis
    component: ignis
spec:
  type: ClusterIP
  selector:
    app: ignis
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http

