apiVersion: v1
kind: Service
metadata:
  name: ignition-service
  namespace: lumines
  labels:
    app: ignition
    component: ignition
spec:
  type: ClusterIP
  selector:
    app: ignition
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http

