apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lumines-services
  namespace: lumines
  labels:
    app: lumines
spec:
  selector:
    matchLabels:
      app: lumines
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

