apiVersion: v1
kind: Service
metadata:
  name: slate-service
  namespace: lumines
  labels:
    app: slate
    component: slate
spec:
  type: ClusterIP
  selector:
    app: slate
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http

