apiVersion: v1
kind: Service
metadata:
  name: spark-service
  namespace: lumines
  labels:
    app: spark
    component: spark
spec:
  type: ClusterIP
  selector:
    app: spark
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http

